import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { useParams, useLocation } from 'wouter';
import { useTranslation } from 'react-i18next';
import { ArrowLeft, Download, MessageCircle, ZoomIn, ChevronLeft, ChevronRight, X } from 'lucide-react';
import { createImageErrorHandler } from '../utils/imageUtils';
import { WA_URL } from '../config';

export default function GalleryPage() {
  const { category } = useParams();
  const [, setLocation] = useLocation();
  const [searchParams] = useSearchParams();
  const { t, i18n } = useTranslation('products');
  const [images, setImages] = useState([]);
  const [manifest, setManifest] = useState(null);
  const [selectedSub, setSelectedSub] = useState('all');
  const [selectedImage, setSelectedImage] = useState(null);

  // Get categories from translation data to stay in sync with ProductsPage
  const categories = useMemo(() => t('categories', { returnObjects: true }) || [], [t]);
  
  // Memoize cat to prevent infinite re-renders
  const cat = useMemo(() => {
    return categories.find(c => c.folderPath === category);
  }, [categories, category]);

  // Filter logic for subcategories - moved up before callbacks
  const filteredImages = useMemo(() => {
    return selectedSub === 'all'
      ? images
      : images.filter(img => img.subcategory === selectedSub);
  }, [selectedSub, images]);

  // Load generated manifest (optional) to avoid relying on sequential filenames
  useEffect(() => {
    let mounted = true;
    fetch('/images/products/manifest.json')
      .then(res => { if (!res.ok) throw new Error('no manifest'); return res.json(); })
      .then(data => { if (mounted) setManifest(data); })
      .catch(() => { if (mounted) setManifest(null); });
    return () => { mounted = false; };
  }, []);

  // Navigation functions wrapped with useCallback for stable references
  const navigateToNextImage = useCallback(() => {
    if (filteredImages.length === 0) return;
    const currentIndex = filteredImages.findIndex(img => img.src === selectedImage.src);
    const nextIndex = (currentIndex + 1) % filteredImages.length;
    setSelectedImage(filteredImages[nextIndex]);
  }, [filteredImages, selectedImage]);

  const navigateToPreviousImage = useCallback(() => {
    if (filteredImages.length === 0) return;
    const currentIndex = filteredImages.findIndex(img => img.src === selectedImage.src);
    const prevIndex = (currentIndex - 1 + filteredImages.length) % filteredImages.length;
    setSelectedImage(filteredImages[prevIndex]);
  }, [filteredImages, selectedImage]);

  const closeLightbox = useCallback(() => {
    setSelectedImage(null);
  }, []);

  // Keyboard controls for lightbox
  useEffect(() => {
    if (!selectedImage) return;

    const handleKeyPress = (event) => {
      switch (event.key) {
        case 'Escape':
          closeLightbox();
          break;
        case 'ArrowLeft':
          event.preventDefault();
          navigateToPreviousImage();
          break;
        case 'ArrowRight':
          event.preventDefault();
          navigateToNextImage();
          break;
        default:
          break;
      }
    };

    document.addEventListener('keydown', handleKeyPress);
    document.body.style.overflow = 'hidden';

    return () => {
      document.removeEventListener('keydown', handleKeyPress);
      document.body.style.overflow = 'unset';
    };
  }, [selectedImage, navigateToNextImage, navigateToPreviousImage, closeLightbox]);

  useEffect(() => {
    // Compute image list for the current category - prefer manifest if present
    if (!cat) {
      setImages([]);
      setSelectedSub('all');
      return;
    }

    const base = `/images/products/architecture/${category}`;
    const imgs = [];

    // If we have a manifest (generated by scripts/generateImageManifest.cjs), use it to list available images per folder.
    if (manifest && manifest.folders) {
      const folderList = manifest.folders[category] || [];
      if (folderList.length > 0) {
        // folderList contains all images in the category folder and its subfolders
        folderList.forEach((entry) => {
          // entry.path is like /images/products/architecture/<category>/[sub]/file.jpg
          const rel = entry.path.replace(`${manifest.root}/${category}/`, '');
          const segments = rel.split('/');
          
          let subId = 'main';
          let subName = cat.title;
          
          // If there's more than one segment, the first is the subfolder
          if (segments.length > 1 && segments[0]) {
            subId = segments[0];
            subName = segments[0];
            
            // Convert subfolder name to human-readable subcategory name if it matches known patterns
            if (cat.sub && cat.sub.length > 0) {
              const matchingSub = cat.sub.find(sub => {
                const normalizedSub = sub.toLowerCase().replace(/[^a-z0-9]/g, '-').replace(/-+/g, '-').replace(/-$/, '');
                return normalizedSub === subId || subId.includes(normalizedSub) || normalizedSub.includes(subId);
              });
              if (matchingSub) {
                subName = matchingSub;
              }
            }
          }
          
          imgs.push({ src: entry.path, alt: entry.name, subcategory: subId, subcategoryName: subName });
        });
      }
    }

    // Fallback to previous sequential behavior if no manifest entries found
    if (imgs.length === 0) {
      if (cat.sub && cat.sub.length > 0) {
        cat.sub.forEach((sub) => {
          const subId = sub.toLowerCase().replace(/[^a-z0-9]/g, '-').replace(/-+/g, '-').replace(/-$/, '');
          for (let i = 1; i <= 50; i++) {
            imgs.push({ src: `${base}/${subId}/${i}.jpg`, alt: `${cat.title} - ${sub} #${i}`, subcategory: subId, subcategoryName: sub });
          }
        });
      } else {
        for (let i = 1; i <= 100; i++) {
          imgs.push({ src: `${base}/${i}.jpg`, alt: `${cat.title} #${i}`, subcategory: 'main', subcategoryName: cat.title });
        }
      }
    }

    setImages(imgs);
    
    // Set initial subcategory from URL params
    const subcategoryParam = searchParams.get('subcategory');
    if (subcategoryParam && cat.sub) {
      const subId = subcategoryParam.toLowerCase().replace(/[^a-z0-9]/g, '-').replace(/-+/g, '-').replace(/-$/, '');
      const validSubcategory = cat.sub.find(sub => {
        const subIdFromName = sub.toLowerCase().replace(/[^a-z0-9]/g, '-').replace(/-+/g, '-').replace(/-$/, '');
        return subIdFromName === subId;
      });
      setSelectedSub(validSubcategory ? subId : 'all');
    } else {
      setSelectedSub('all');
    }
  }, [category, searchParams, cat, manifest]);

  // WhatsApp with improved message template
  const shareOnWhatsApp = (img, catName, subName) => {
    const currentUrl = window.location.href;
    const productName = `${catName} - ${subName}`;
    const message = `Hello Abdulhaq Dimensions, I'm interested in: • Product: ${productName} • SKU/Ref: Gallery Item • URL: ${currentUrl}`;
    const url = WA_URL ? WA_URL(message) : undefined;
    if (url) window.open(url, '_blank', 'noopener,noreferrer');
  };

  const dir = (i18n && typeof i18n.dir === 'function')
    ? i18n.dir()
    : (i18n && typeof i18n.language === 'string' && i18n.language.startsWith('ar') ? 'rtl' : 'ltr');

  if (!cat)
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="text-center">
          <p className="text-red-600 font-semibold text-xl mb-3">Category not found</p>
          <button
            onClick={() => setLocation('/products')}
            className="text-teal-700 hover:text-teal-800 underline decoration-1 underline-offset-2"
          >← Back to Products</button>
        </div>
      </div>
    );

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      {/* Header */}
      <div className="bg-white dark:bg-gray-800 shadow-sm border-b border-gray-200 dark:border-gray-700">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <button
            onClick={() => setLocation('/products')}
            aria-label={t('backToProducts', { defaultValue: 'Back to Products' })}
            className={`flex items-center ${dir === 'rtl' ? 'flex-row-reverse' : ''} text-gray-600 dark:text-gray-300 hover:text-teal-600 dark:hover:text-teal-400 transition`}
            style={{ textDecoration: 'none' }}
          >
            <ArrowLeft className={`w-5 h-5 ${dir === 'rtl' ? 'ml-2' : 'mr-2'}`} />
            <span className="underline decoration-0">Back to Products</span>
          </button>
          <div className="text-center flex-1">
            <h1 className="text-2xl font-bold text-gray-800 dark:text-gray-200">{cat.title}</h1>
            {/* images count removed per request */}
          </div>
          <div className="w-24" /> {/* Spacer */}
        </div>
      </div>

      {/* Subcategory filter */}
      {cat.sub && cat.sub.length > 1 && (
        <div className="bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700">
          <div className="container mx-auto px-4 py-4 flex gap-2 flex-wrap justify-center">
            <button
              onClick={() => {
                setSelectedSub('all');
                setLocation(`/gallery/${category}`, { replace: true });
              }}
              className={`px-4 py-2 rounded-full text-sm font-medium ${selectedSub === 'all'
                ? 'bg-teal-600 text-white'
                : 'bg-gray-200 dark:bg-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-300 dark:hover:bg-gray-600'
                }`}
            >
              All
              <span className="sr-only">{images.length} {"items"}</span>
            </button>
            {cat.sub.map(sub => {
              const count = images.filter(i => i.subcategory === sub.toLowerCase().replace(/[^a-z0-9]/g, '-').replace(/-+/g, '-').replace(/-$/, '')).length;
              return (
                  <button
                  key={sub}
                  onClick={() => {
                    setSelectedSub(sub.toLowerCase().replace(/[^a-z0-9]/g, '-').replace(/-+/g, '-').replace(/-$/, ''));
                    setLocation(`/gallery/${category}?subcategory=${sub.toLowerCase().replace(/[^a-z0-9]/g, '-').replace(/-+/g, '-').replace(/-$/, '')}`, { replace: true });
                  }}
                  className={`px-4 py-2 rounded-full text-sm font-medium ${selectedSub === sub.toLowerCase().replace(/[^a-z0-9]/g, '-').replace(/-+/g, '-').replace(/-$/, '')
                    ? 'bg-teal-600 text-white'
                    : 'bg-gray-200 dark:bg-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-300 dark:hover:bg-gray-600'
                    }`}
                >
                  {sub}
                  <span className="sr-only">{count} {"items"}</span>
                </button>
              );
            })}
          </div>
        </div>
      )}

      {/* Gallery */}
      <div className="container mx-auto px-4 py-8">
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
          {filteredImages.map((img, idx) => (
            <div
              key={idx}
              className="group relative bg-white dark:bg-gray-800 rounded-lg shadow-md overflow-hidden hover:shadow-xl transition-all cursor-pointer"
              onClick={() => setSelectedImage(img)}
            >
              <div className="aspect-square overflow-hidden">
                <img
                  src={img.src}
                  alt={img.alt || cat.title}
                  loading="lazy"
                  className="w-full h-full object-cover group-hover:scale-105 transition-transform"
                  onError={createImageErrorHandler('product')}
                />
              </div>
              <div className="p-3">
                <p className="text-xs font-medium text-gray-700 dark:text-gray-300">{img.subcategoryName}</p>
              </div>
              {/* Overlay */}
              <div className="absolute inset-0 bg-black bg-opacity-0 group-hover:bg-opacity-40 transition flex items-center justify-center">
                <div className="opacity-0 group-hover:opacity-100 flex space-x-2">
                  <button
                    className="bg-white dark:bg-gray-700 text-gray-800 dark:text-gray-200 p-2 rounded-full hover:bg-gray-100 dark:hover:bg-gray-600"
                    onClick={e => {
                      e.stopPropagation();
                      setSelectedImage(img);
                    }}
                    tabIndex={-1}
                  >
                    <ZoomIn className="w-5 h-5" />
                  </button>
                  <button
                    className="bg-green-500 text-white p-2 rounded-full hover:bg-green-600"
                    onClick={e => {
                      e.stopPropagation();
                      shareOnWhatsApp(img.src, cat.title, img.subcategoryName);
                    }}
                    tabIndex={-1}
                  ><MessageCircle className="w-5 h-5" /></button>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
      {/* Enhanced Image Lightbox Modal */}
      {selectedImage && (
        <div className="fixed inset-0 bg-black/95 z-50 flex items-center justify-center p-4">
          <div className="relative w-full h-full max-w-6xl max-h-[90vh] flex flex-col">
            {/* Header with close button and image counter */}
            <div className="flex justify-between items-center mb-4 px-2">
              <div className="text-white text-lg font-medium">
                {selectedImage.subcategoryName} - {cat.title}
              </div>
              <div className="flex items-center gap-4">
                <div className="text-white/70 text-sm">
                  {filteredImages.findIndex(img => img.src === selectedImage.src) + 1} / {filteredImages.length}
                </div>
                <button
                  onClick={closeLightbox}
                  className="text-white bg-black/30 hover:bg-black/50 rounded-full p-2 transition-colors"
                  aria-label="Close lightbox"
                >
                  <X className="w-6 h-6" />
                </button>
              </div>
            </div>

            {/* Main image container */}
            <div className="flex-1 relative flex items-center justify-center">
              <img
                src={selectedImage.src}
                alt={selectedImage.alt}
                loading="lazy"
                className="max-w-full max-h-full object-contain rounded-lg shadow-2xl"
                onError={createImageErrorHandler('product')}
              />
              
              {/* Navigation arrows */}
              {filteredImages.length > 1 && (
                <>
                  <button
                    onClick={navigateToPreviousImage}
                    className="absolute left-4 top-1/2 -translate-y-1/2 bg-black/30 hover:bg-black/50 text-white p-3 rounded-full transition-all duration-200"
                    aria-label="Previous image"
                  >
                    <ChevronLeft className="w-6 h-6" />
                  </button>
                  <button
                    onClick={navigateToNextImage}
                    className="absolute right-4 top-1/2 -translate-y-1/2 bg-black/30 hover:bg-black/50 text-white p-3 rounded-full transition-all duration-200"
                    aria-label="Next image"
                  >
                    <ChevronRight className="w-6 h-6" />
                  </button>
                </>
              )}
            </div>

            {/* Action buttons */}
            <div className="flex justify-center gap-4 mt-4">
              <button
                onClick={() => shareOnWhatsApp(selectedImage.src, cat.title, selectedImage.subcategoryName)}
                className="bg-green-500 hover:bg-green-600 text-white px-4 py-2 rounded-lg transition-colors flex items-center gap-2"
              >
                <MessageCircle className="w-5 h-5" />
                <span>Order Now</span>
              </button>
              <button
                onClick={() => {
                  const link = document.createElement('a');
                  link.href = selectedImage.src;
                  link.download = `${cat.title}-${selectedImage.subcategoryName}.jpg`;
                  link.click();
                }}
                className="bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-lg transition-colors flex items-center gap-2"
              >
                <Download className="w-5 h-5" />
                <span>Download</span>
              </button>
            </div>

            {/* Thumbnail strip */}
            {filteredImages.length > 1 && (
              <div className="mt-6 max-w-4xl mx-auto">
                <div className="flex gap-2 justify-center overflow-x-auto pb-2 scrollbar-hide">
                  {filteredImages.map((img, index) => (
                    <button
                      key={index}
                      onClick={() => setSelectedImage(img)}
                      className={`flex-shrink-0 w-16 h-16 rounded-lg overflow-hidden border-2 transition-all duration-200 ${
                        img.src === selectedImage.src 
                          ? 'border-white shadow-lg scale-110' 
                          : 'border-white/30 hover:border-white/60'
                      }`}
                    >
                      <img
                        src={img.src}
                        alt={`Thumbnail ${index + 1}`}
                        loading="lazy"
                        className="w-full h-full object-cover"
                        onError={createImageErrorHandler('product')}
                      />
                    </button>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
